"""Build the M1 dataset: fetch -> verify coverage -> normalize -> quality-check.

    uv run python -m goalline.data.cli

Writes the normalized dataset to the git-ignored data cache and a derived
coverage report (aggregate stats only — safe to commit) to reports/.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from .coverage import column_coverage
from .fetch import fetch_all
from .ingest import build_dataset
from .quality import check_dataset
from .sources import all_sources


def main() -> int:
    ap = argparse.ArgumentParser(description="Build the Milestone 1 dataset.")
    ap.add_argument("--cache", type=Path, default=Path("data/raw"))
    ap.add_argument("--out", type=Path, default=Path("data/processed/m1_dataset.parquet"))
    ap.add_argument("--report", type=Path, default=Path("reports/m1_data_coverage.md"))
    ap.add_argument("--force", action="store_true", help="re-download even if cached")
    args = ap.parse_args()

    sources = all_sources()

    print(f"Fetching {len(sources)} files from football-data.co.uk ...")
    fetch_all(args.cache, sources, force=args.force)

    print("\nColumn coverage (audit verification):")
    cov = column_coverage(args.cache, sources)
    print(cov.to_string(index=False))

    print("\nBuilding normalized dataset ...")
    df = build_dataset(args.cache, sources)
    by_src = df.groupby("ou_source", dropna=False).size().to_dict()
    n_seasons, n_leagues = df["season"].nunique(), df["league"].nunique()
    print(f"  {len(df)} matches | {n_seasons} seasons | {n_leagues} leagues")
    print(f"  O/U odds provenance: {by_src}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    df.to_parquet(args.out)
    print(f"  wrote {args.out}")

    print("\nQuality checks:")
    report = check_dataset(df)
    for name, passed, detail in report.checks:
        flag = "PASS" if passed else "FAIL"
        print(f"  [{flag}] {name}" + (f"  ({detail})" if not passed else ""))
    print(f"\nOverall: {'OK' if report.ok else 'ISSUES FOUND'}")

    _write_report(args.report, cov, df, report)
    print(f"Wrote coverage report -> {args.report}")
    return 0 if report.ok else 1


def _write_report(path: Path, cov, df, report) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Milestone 1 — data coverage (derived; safe to commit)",
        "",
        "Generated by `goalline.data.cli`. Aggregate statistics only — no raw odds.",
        "",
        "## Per league-season column coverage",
        "",
        cov.to_markdown(index=False),
        "",
        "## Normalized dataset",
        "",
        f"- Matches: {len(df)}",
        f"- Seasons: {df['season'].nunique()}  ({df['season'].min()}–{df['season'].max()})",
        f"- O/U odds provenance: {df.groupby('ou_source', dropna=False).size().to_dict()}",
        "",
        "## Quality checks",
        "",
    ]
    for name, passed, detail in report.checks:
        suffix = "" if passed else f" — {detail}"
        lines.append(f"- [{'PASS' if passed else 'FAIL'}] {name}{suffix}")
    path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    raise SystemExit(main())
